# nixpacks.toml
[variables]
MIX_ENV = 'production'

[phases.setup]
nixPkgs = ['elixir']

[phases.install]
cmds = [mix local.hex --force', 'mix local.rebar --force', 'mix deps.get --only prod']

[phases.build]
cmds = ['mix compile', 'mix assets.deploy']

[start]
cmds = ['mix ecto.setup', 'mix phx.server'] 